# multi-stage build custom image to hide the scenario setup
image: leskis/sadpod-docker-base:latest

tasks:
  - name: start the exercise
    # clean up the terminal a bit
    command: clear && echo "start the activity!"
